FROM golang:1.23-alpine AS builder

RUN apk add --no-cache git ca-certificates tzdata

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /flux-worker-rss ./cmd/worker-rss/

# ---

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata && \
    adduser -D -h /app flux

COPY --from=builder /flux-worker-rss /usr/local/bin/flux-worker-rss

USER flux
WORKDIR /app

ENTRYPOINT ["flux-worker-rss"]
