DELETE FROM sources
WHERE source_type IN ('rss', 'hn')
  AND name IN (
    'tl;dr sec',
    'Krebs on Security',
    'The Hacker News',
    'BleepingComputer',
    'Schneier on Security',
    'SANS Internet Storm Center',
    'Troy Hunt',
    'Daniel Miessler',
    'Risky Business',
    'TLDR InfoSec',
    'Dark Reading',
    'OpenShift Security Advisories',
    'TLDR Newsletter',
    'TLDR AI',
    'Ars Technica',
    'The Verge',
    'Lobsters',
    'LWN.net',
    'Go Blog',
    'Kubernetes Blog',
    'Red Hat OpenShift Blog',
    'Red Hat Developer Blog',
    'stderr.at',
    'OKD Blog',
    'Papers We Love',
    'Ollama Blog',
    'Anthropic News',
    'Anthropic Engineering',
    'Anthropic Research',
    'Anthropic Frontier Red Team',
    'Claude Blog',
    'Claude Code Changelog',
    'OpenAI News',
    'OpenAI Research',
    'xAI News',
    'Google DeepMind',
    'TLDR Founders',
    'Bloomberg Technology',
    'Reuters Business',
    'CNBC Tech',
    'CoinDesk',
    'The Block',
    'Finimize',
    'Financial Times Tech',
    'Expansion',
    'Reuters Top News',
    'BBC World News',
    'AP News',
    'El Pais Internacional',
    'The Guardian World',
    'Al Jazeera',
    'Hacker News'
);
